DROP DATABASE IF EXISTS b_20211120;
DROP DATABASE IF EXISTS a1;

CREATE DATABASE a1;

USE a1;

CREATE TABLE t_addr (
	idx INT PRIMARY KEY AUTO_INCREMENT,
	'name' VARCHAR(30) NOT NULL,
	address VARCHAR (100) NOT NULL,
	phone VARCHAR (15) NOT NULL
);

DESC t_addr;